



- 异常处理
> 即便Python程序的语法是正确的，在运行它的时候，也有可能发生错误。运行期检测到的错误被称为异常。
> 大多数的异常都不会被程序处理，都以错误信息的形式展现在这里

==方式一 自己处理异常==

```
# 语法规则 try...except...finally..          try...finally             try...except...
def test():
    a=1
    b=0
    try:
        c=a/b
        return
    except Exception as e:            # 捕获异常 Exception 是所有异常的父类 
        print(e)
        return
    finally:                          # finally 会在 return 前面执行
        print('end')

test()
```

==方式二 抛出异常==

```python
def test():
    print('1111')
    raise Exception('错误')    # 抛出异常  程序中断
    # print('2222')              不会执行


def a():
    try:
        test()
    except Exception as e:
        raise Exception('把异常抛给别人')     # 自己不处理 抛给别人 
    finally:
        print('end')           # 还是会执行

a()
```

- 自定义异常

```python
# 自定义异常: 业务异常
class AgeExcept(Exception):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

def big17(age):
    if age < 18:
        raise AgeExcept('要求输入的值大于17')
    else:
        return age

try :	
	big17(1)
except AgeExcept as e:
	print(e)
```